#!/bin/bash
. /home/pi/env_vars
NOW=`date +"%H"`
echo NOW=$NOW
echo ON=$ON
echo OFF=$OFF
if [ $NOW -ge $OFF ] && [ $NOW -lt $ON ]; then
  echo "OFF"
  /home/pi/led 0
  /home/pi/hps 0
else
  echo "ON"
  /home/pi/led 1
  /home/pi/hps 1
fi
